// <auto-generated />
namespace LoginSecure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initdbagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdbagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201810150247067_init-db-again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
